### ISSUE TITLE
Two errors in notebook

### ISSUE THREAD

**Issue by Ali762** [sadnow/360Diffusion#3]
Running the notebook as-is on colab pro, I get the following errors:

Current upscale target is  /content/drive/MyDrive/MyName/Diffusion/existential/existentialbatch0000_iteration0021_output0000_211217-112807_637275_out.png
next_outscale is 2
usage: inference_realesrgan.py [-h] [-i INPUT] [-n MODEL_NAME] [-o OUTPUT]
                               [-s OUTSCALE] [--suffix SUFFIX] [-t TILE]
                               [--tile_pad TILE_PAD] [--pre_pad PRE_PAD]
                               [--face_enhance] [--half]
                               [--alpha_upsampler ALPHA_UPSAMPLER] [--ext EXT]
inference_realesrgan.py: error: unrecognized arguments: --model_path /content/Real-ESRGAN/experiments/pretrained_models/RealESRGAN_x4plus.pth

 ERROR: CAN'T FIND UPSCALED FILE  /content/drive/MyDrive/MyName/Diffusion/existential/existentialbatch0000_iteration0021_output0000_211217-112807_637275_out.png

**Comment by pskl** [comment]
Jup same, also theye URL is not accessible

**Comment by sadnow** [comment]
I appreciate the notice! I will look at this shortly and update y'all when it's fixed-

**Comment by sadnow** [comment]
Resolved with a878e68afad1382ddd0c2599d433b2467118da94 ; thanks for the report~
